#!/bin/sh
(
	for i in {0..200}; do
		echo 'GET /'
		sleep 0.1
	done

	for i in {0..3}; do
		COUNT=0;
		cat "$(cd "$(dirname "${0}")"; pwd)/../testdata/images.txt" | grep -v '^#' | while read ns repo tag; do
			manifest_hash="$(curl -svI "$1/v2/$repo/manifests/$tag?ns=$ns" 2>&1 | grep docker-content-digest: | head -n1 | cut -d: -f2- | sed -e 's/^\s\+//' -e 's/\s\+$//')";
			curl -s "$1/v2/$repo/manifests/$manifest_hash?ns=$ns" | jq -r '.manifests[].digest' | while read manifest_hash; do
				curl -s "$1/v2/$repo/manifests/$manifest_hash?ns=$ns" | jq -r '.config.digest, .layers[].digest' | while read blob_hash; do
					echo "GET /v2/$repo/blobs/$blob_hash?ns=$ns";
				done &
				echo 'GET /';
			done &
			echo 'GET /';
		done

		for i in {0..500}; do
			echo 'GET /'
			sleep 0.1
		done
	done
) | xargs -n2 -P40 bash -c 'curl -o /dev/null -X "${1}" "'"${1}"'${2}" &>/dev/null; echo $? $@' argv0

